### ISSUE TITLE
abgabe 3

### ISSUE THREAD

**Issue by jschleutker** [fwilke/webtech#3]
ich habe meine sache jetzt fast fertig. es funktioniert soweit. mir fehlt allerdings noch das mit dem bild laden in der letzten teilaufgabe. 
meins ist jetzt sicherlich nicht von überrangeder qualität. dafür fehlte mir auch ein wenig die zeit js vernünftig zu begreifen. allerdings würde ich gerne von ihm feedback bekommen. wollen wir dann später meins nehmen?
@fwilke

**Comment by fwilke** [comment]
Können wir machen, wenn du es kommentierst :P

**Comment by jschleutker** [comment]
ja, wird bis Donnerstag nachgeholt. Donnerstag Mittag würde ich sagen abschicken.

**Comment by jschleutker** [comment]
So, sollte jetzt alles funktionieren. Ich garantieren nicht für schönen Code oder ähnliches :p 
Kannst das ja mal kurz eine Review unterziehen. Geändert ist auch wirklich nur eine JS Datei.
